// Конфигурация API
const API_BASE_URL = 'http://localhost:3000';

// helpers for storing the current user between pages
const auth = window.auth || {
    getCurrentUser: () => {
        try {
            const raw = localStorage.getItem('currentUser');
            return raw ? JSON.parse(raw) : null;
        } catch (e) {
            console.warn('Unable to read current user', e);
            return null;
        }
    },
    saveCurrentUser: (user) => {
        try {
            localStorage.setItem('currentUser', JSON.stringify(user));
        } catch (e) {
            console.warn('Unable to save user', e);
        }
    },
    clearCurrentUser: () => {
        localStorage.removeItem('currentUser');
    },
    isAdmin: (user) => {
        const role = (user?.role || "").toLowerCase();
        const adminRoles = ['admin', 'administrator', 'администратор'];
        return adminRoles.includes(role);
    },
    isCustomer: (user) => {
        const role = (user?.role || "").toLowerCase();
        const customerRoles = ['customer', 'client', 'покупатель', 'клиент'];
        return customerRoles.includes(role);
    }
};

// TOP-100 самых распространенных паролей 2024 года
const TOP_PASSWORDS = [
    'password', '123456', '123456789', '12345678', '12345', '1234567', '1234567890',
    'qwerty', 'abc123', '111111', '123123', 'admin', 'letmein', 'welcome',
    'monkey', '1234567890', 'password1', '1234', 'qwerty123', '000000', '123',
    'dragon', 'sunshine', 'princess', 'football', 'iloveyou', 'master', 'hello',
    'freedom', 'whatever', 'qazwsx', 'trustno1', '654321', 'jordan23', 'harley',
    'password123', 'hunter', 'robert', 'matthew', 'jordan', 'michelle', 'charlie',
    'andrew', 'daniel', 'mark', 'joshua', 'jennifer', 'thomas', 'christopher',
    'amanda', 'jessica', 'tyler', 'michael', 'david', 'james', 'john', 'robert',
    'william', 'richard', 'joseph', 'charles', 'thomas', 'daniel', 'matthew',
    'anthony', 'mark', 'donald', 'steven', 'paul', 'andrew', 'joshua', 'kenneth',
    'kevin', 'brian', 'george', 'timothy', 'ronald', 'jason', 'edward', 'jeffrey',
    'ryan', 'jacob', 'gary', 'nicholas', 'eric', 'jonathan', 'stephen', 'larry',
    'justin', 'scott', 'brandon', 'benjamin', 'samuel', 'frank', 'gregory', 'raymond',
    'alexander', 'patrick', 'jack', 'dennis', 'jerry', 'tyler', 'aaron', 'jose',
    'henry', 'adam', 'douglas', 'nathan', 'zachary', 'kyle', 'noah', 'ethan'
];

// Глобальные переменные
let usernameGenerationAttempts = 5;
let autoGeneratedPassword = '';

// Инициализация
document.addEventListener('DOMContentLoaded', () => {
    setupForm();
    setupPhoneMask();
    setupPasswordTypeToggle();
    setupUsernameGeneration();
    setupFormValidation();
});

// Настройка формы
function setupForm() {
    const form = document.getElementById('register-form');
    if (form) {
        form.addEventListener('submit', handleSubmit);
    }
}

// Маска для телефона РБ
function setupPhoneMask() {
    const phoneInput = document.getElementById('phone');
    if (phoneInput) {
        phoneInput.addEventListener('input', (e) => {
            let value = e.target.value.replace(/\D/g, '');
            if (value.startsWith('375')) {
                value = value.substring(3);
            }
            if (value.length > 0) {
                value = '+375 ' + value;
                if (value.length > 7) {
                    value = value.substring(0, 7) + ' (' + value.substring(7);
                }
                if (value.length > 12) {
                    value = value.substring(0, 12) + ') ' + value.substring(12);
                }
                if (value.length > 17) {
                    value = value.substring(0, 17) + '-' + value.substring(17, 19) + '-' + value.substring(19, 21);
                }
            } else {
                value = '+375 ';
            }
            e.target.value = value;
            validateField('phone');
        });
    }
}

// Переключение типа пароля
function setupPasswordTypeToggle() {
    const manualRadio = document.getElementById('password-manual');
    const autoRadio = document.getElementById('password-auto');
    const manualSection = document.getElementById('manual-password-section');
    const autoSection = document.getElementById('auto-password-section');
    
    if (manualRadio && autoRadio) {
        manualRadio.addEventListener('change', () => {
            if (manualRadio.checked) {
                manualSection.style.display = 'block';
                autoSection.style.display = 'none';
                document.getElementById('password').required = true;
                document.getElementById('password-confirm').required = true;
            }
        });
        
        autoRadio.addEventListener('change', () => {
            if (autoRadio.checked) {
                manualSection.style.display = 'none';
                autoSection.style.display = 'block';
                document.getElementById('password').required = false;
                document.getElementById('password-confirm').required = false;
                generateAutoPassword();
            }
        });
    }
    
    // Кнопка копирования пароля
    const copyBtn = document.getElementById('copy-password-btn');
    if (copyBtn) {
        copyBtn.addEventListener('click', () => {
            const passwordField = document.getElementById('auto-password');
            if (passwordField) {
                passwordField.select();
                document.execCommand('copy');
                copyBtn.textContent = 'Скопировано!';
                setTimeout(() => {
                    copyBtn.textContent = 'Копировать';
                }, 2000);
            }
        });
    }
}

// Генерация автоматического пароля
function generateAutoPassword() {
    const length = 12;
    const uppercase = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const lowercase = 'abcdefghijklmnopqrstuvwxyz';
    const numbers = '0123456789';
    const special = '!@#$%^&*()_+-=[]{}|;:,.<>?';
    const all = uppercase + lowercase + numbers + special;
    
    let password = '';
    password += uppercase[Math.floor(Math.random() * uppercase.length)];
    password += lowercase[Math.floor(Math.random() * lowercase.length)];
    password += numbers[Math.floor(Math.random() * numbers.length)];
    password += special[Math.floor(Math.random() * special.length)];
    
    for (let i = password.length; i < length; i++) {
        password += all[Math.floor(Math.random() * all.length)];
    }
    
    // Перемешиваем
    password = password.split('').sort(() => Math.random() - 0.5).join('');
    
    autoGeneratedPassword = password;
    const passwordField = document.getElementById('auto-password');
    if (passwordField) {
        passwordField.value = password;
    }
}

// Генерация никнейма
async function generateUsername() {
    const firstname = document.getElementById('firstname').value.trim();
    const lastname = document.getElementById('lastname').value.trim();
    
    if (!firstname || !lastname) {
        showError('username', 'Сначала заполните имя и фамилию');
        return;
    }
    
    let attempts = 0;
    const maxAttempts = 10;
    let username = '';
    let isUnique = false;
    
    while (!isUnique && attempts < maxAttempts) {
        const suffixes = ['_', '-', '', 'X', 'Pro', '2024'];
        const suffix = suffixes[Math.floor(Math.random() * suffixes.length)];
        
        // Берем первые 1-3 буквы имени
        const nameLength = Math.min(3, Math.floor(Math.random() * 3) + 1);
        const namePart = firstname.substring(0, nameLength);
        // Берем первые 1-3 буквы фамилии
        const surnameLength = Math.min(3, Math.floor(Math.random() * 3) + 1);
        const surnamePart = lastname.substring(0, surnameLength);
        // Случайное число от 10 до 999
        const number = Math.floor(Math.random() * 990) + 10;
        
        username = namePart + surnamePart + number;
        if (suffix && Math.random() > 0.5) {
            username += suffix;
        }
        
        // Проверяем уникальность
        isUnique = await checkUsernameUnique(username);
        attempts++;
    }
    
    if (isUnique) {
        document.getElementById('username').value = username;
        validateField('username');
    } else {
        // Если не удалось сгенерировать уникальный, разрешаем ручной ввод
        usernameGenerationAttempts = 0;
        updateUsernameAttempts();
        showError('username', 'Не удалось сгенерировать уникальный никнейм. Введите вручную.');
    }
}

// Проверка уникальности никнейма
async function checkUsernameUnique(username) {
    try {
        const response = await fetch(`${API_BASE_URL}/users?username=${username}`);
        if (response.ok) {
            const users = await response.json();
            return users.length === 0;
        }
        return true;
    } catch (error) {
        console.error('Ошибка при проверке никнейма:', error);
        return true;
    }
}

// Настройка генерации никнейма
function setupUsernameGeneration() {
    const generateBtn = document.getElementById('generate-username-btn');
    const usernameInput = document.getElementById('username');
    
    if (generateBtn) {
        generateBtn.addEventListener('click', async () => {
            if (usernameGenerationAttempts > 0) {
                usernameGenerationAttempts--;
                updateUsernameAttempts();
                await generateUsername();
            } else {
                // Разрешаем ручной ввод
                usernameInput.removeAttribute('readonly');
                usernameInput.focus();
                document.getElementById('username-hint').textContent = 'Введите никнейм вручную';
                generateBtn.style.display = 'none';
            }
        });
    }
    
    // При изменении имени/фамилии сбрасываем попытки
    ['firstname', 'lastname'].forEach(id => {
        const input = document.getElementById(id);
        if (input) {
            input.addEventListener('input', () => {
                usernameGenerationAttempts = 5;
                updateUsernameAttempts();
                if (usernameInput.hasAttribute('readonly')) {
                    usernameInput.value = '';
                }
            });
        }
    });
}

// Обновление счетчика попыток
function updateUsernameAttempts() {
    const attemptsSpan = document.getElementById('username-attempts');
    if (attemptsSpan) {
        attemptsSpan.textContent = usernameGenerationAttempts;
        if (usernameGenerationAttempts === 0) {
            const usernameInput = document.getElementById('username');
            if (usernameInput) {
                usernameInput.removeAttribute('readonly');
                usernameInput.focus();
            }
            document.getElementById('username-hint').textContent = 'Введите никнейм вручную';
            document.getElementById('generate-username-btn').style.display = 'none';
        }
    }
}

// Валидация полей
function validateField(fieldName) {
    const field = document.getElementById(fieldName);
    const errorElement = document.getElementById(`${fieldName}-error`);
    
    if (!field || !errorElement) return false;
    
    let isValid = true;
    let errorMessage = '';
    
    switch (fieldName) {
        case 'lastname':
        case 'firstname':
            if (!field.value.trim()) {
                isValid = false;
                errorMessage = 'Это поле обязательно для заполнения';
            } else if (field.value.trim().length < 2) {
                isValid = false;
                errorMessage = 'Минимум 2 символа';
            }
            break;
            
        case 'phone':
            const phoneRegex = /^\+375\s\(\d{2}\)\s\d{3}-\d{2}-\d{2}$/;
            if (!field.value.trim()) {
                isValid = false;
                errorMessage = 'Это поле обязательно для заполнения';
            } else if (!phoneRegex.test(field.value)) {
                isValid = false;
                errorMessage = 'Неверный формат номера телефона РБ';
            }
            break;
            
        case 'email':
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!field.value.trim()) {
                isValid = false;
                errorMessage = 'Это поле обязательно для заполнения';
            } else if (!emailRegex.test(field.value)) {
                isValid = false;
                errorMessage = 'Неверный формат email';
            }
            break;
            
        case 'birthdate':
            if (!field.value) {
                isValid = false;
                errorMessage = 'Это поле обязательно для заполнения';
            } else {
                const birthDate = new Date(field.value);
                const today = new Date();
                const age = today.getFullYear() - birthDate.getFullYear();
                const monthDiff = today.getMonth() - birthDate.getMonth();
                const actualAge = monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate()) ? age - 1 : age;
                
                if (actualAge < 16) {
                    isValid = false;
                    errorMessage = 'Вам должно быть не менее 16 лет';
                }
            }
            break;
            
        case 'username':
            if (!field.value.trim()) {
                isValid = false;
                errorMessage = 'Это поле обязательно для заполнения';
            } else {
                // Проверка уникальности асинхронно
                checkUsernameUnique(field.value.trim()).then(isUnique => {
                    if (!isUnique) {
                        showError('username', 'Этот никнейм уже занят');
                        field.classList.add('error');
                        checkFormValidity();
                    } else {
                        field.classList.remove('error');
                        document.getElementById('username-error').textContent = '';
                        checkFormValidity();
                    }
                });
            }
            break;
            
        case 'password':
            if (document.getElementById('password-manual').checked) {
                const password = field.value;
                if (!password) {
                    isValid = false;
                    errorMessage = 'Это поле обязательно для заполнения';
                } else if (password.length < 8 || password.length > 20) {
                    isValid = false;
                    errorMessage = 'Пароль должен содержать от 8 до 20 символов';
                } else if (!/(?=.*[a-z])/.test(password)) {
                    isValid = false;
                    errorMessage = 'Пароль должен содержать строчную букву';
                } else if (!/(?=.*[A-Z])/.test(password)) {
                    isValid = false;
                    errorMessage = 'Пароль должен содержать заглавную букву';
                } else if (!/(?=.*\d)/.test(password)) {
                    isValid = false;
                    errorMessage = 'Пароль должен содержать цифру';
                } else if (!/(?=.*[!@#$%^&*()_+\-=\[\]{}|;:,.<>?])/.test(password)) {
                    isValid = false;
                    errorMessage = 'Пароль должен содержать специальный символ';
                } else if (TOP_PASSWORDS.includes(password.toLowerCase())) {
                    isValid = false;
                    errorMessage = 'Этот пароль слишком распространен';
                }
            }
            break;
            
        case 'password-confirm':
            if (document.getElementById('password-manual').checked) {
                const password = document.getElementById('password').value;
                const confirm = field.value;
                if (!confirm) {
                    isValid = false;
                    errorMessage = 'Это поле обязательно для заполнения';
                } else if (password !== confirm) {
                    isValid = false;
                    errorMessage = 'Пароли не совпадают';
                }
            }
            break;
            
        case 'agreement':
            if (!field.checked) {
                isValid = false;
                errorMessage = 'Необходимо согласиться с условиями';
            }
            break;
    }
    
    if (isValid) {
        field.classList.remove('error');
        errorElement.textContent = '';
    } else {
        field.classList.add('error');
        errorElement.textContent = errorMessage;
    }
    
    checkFormValidity();
    return isValid;
}

// Показать ошибку
function showError(fieldName, message) {
    const errorElement = document.getElementById(`${fieldName}-error`);
    const field = document.getElementById(fieldName);
    if (errorElement) {
        errorElement.textContent = message;
    }
    if (field) {
        field.classList.add('error');
    }
    checkFormValidity();
}

// Настройка валидации формы
function setupFormValidation() {
    const inputs = document.querySelectorAll('.form-input, input[type="checkbox"]');
    inputs.forEach(input => {
        input.addEventListener('input', () => {
            if (input.id) {
                validateField(input.id);
            }
        });
        input.addEventListener('blur', () => {
            if (input.id) {
                validateField(input.id);
            }
        });
    });
    
    // Специальная обработка для поля подтверждения пароля (без вставки)
    const passwordConfirm = document.getElementById('password-confirm');
    if (passwordConfirm) {
        passwordConfirm.addEventListener('paste', (e) => {
            e.preventDefault();
            showError('password-confirm', 'Вставка пароля запрещена. Введите пароль вручную.');
        });
    }
    
    // При изменении пароля проверяем подтверждение
    const password = document.getElementById('password');
    if (password) {
        password.addEventListener('input', () => {
            validateField('password');
            validateField('password-confirm');
        });
    }
}

// Проверка валидности всей формы
async function checkFormValidity() {
    const requiredFields = ['lastname', 'firstname', 'phone', 'email', 'birthdate', 'username', 'agreement'];
    const passwordFields = ['password', 'password-confirm'];
    
    let isValid = true;
    
    // Проверяем все обязательные поля
    for (const fieldName of requiredFields) {
        const field = document.getElementById(fieldName);
        if (field && field.hasAttribute('required')) {
            if (fieldName === 'agreement') {
                if (!field.checked) isValid = false;
            } else {
                if (!field.value.trim()) isValid = false;
            }
        }
    }
    
    // Проверяем пароль
    const passwordManual = document.getElementById('password-manual').checked;
    if (passwordManual) {
        for (const fieldName of passwordFields) {
            const field = document.getElementById(fieldName);
            if (field && !field.value.trim()) {
                isValid = false;
            }
        }
        
        const password = document.getElementById('password').value;
        const confirm = document.getElementById('password-confirm').value;
        if (password !== confirm) {
            isValid = false;
        }
    } else {
        // Если автоматический пароль, проверяем что он сгенерирован
        const autoPasswordField = document.getElementById('auto-password');
        if (!autoPasswordField || !autoPasswordField.value) {
            isValid = false;
        } else {
            autoGeneratedPassword = autoPasswordField.value;
        }
    }
    
    // Проверяем отсутствие ошибок
    const errors = document.querySelectorAll('.error-message');
    errors.forEach(error => {
        if (error.textContent.trim()) {
            isValid = false;
        }
    });
    
    // Проверяем уникальность никнейма
    const username = document.getElementById('username').value.trim();
    if (username) {
        const isUnique = await checkUsernameUnique(username);
        if (!isUnique) {
            isValid = false;
        }
    }
    
    // Активируем/деактивируем кнопку
    const registerBtn = document.getElementById('register-btn');
    if (registerBtn) {
        registerBtn.disabled = !isValid;
    }

    return isValid;
}

// Обработка отправки формы
async function handleSubmit(e) {
    e.preventDefault();
    
    const isValid = await checkFormValidity();
    if (!isValid) {
        return;
    }
    
    const passwordType = document.querySelector('input[name="password-type"]:checked').value;
    const password = passwordType === 'auto' ? autoGeneratedPassword : document.getElementById('password').value;
    
    const userData = {
        lastname: document.getElementById('lastname').value.trim(),
        firstname: document.getElementById('firstname').value.trim(),
        middlename: document.getElementById('middlename').value.trim() || null,
        phone: document.getElementById('phone').value.trim(),
        email: document.getElementById('email').value.trim(),
        birthdate: document.getElementById('birthdate').value,
        username: document.getElementById('username').value.trim(),
        password: password,
        role: 'customer',
        registeredAt: new Date().toISOString()
    };
    
    try {
        const response = await fetch(`${API_BASE_URL}/users`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(userData)
        });
        
        if (response.ok) {
            const createdUser = await response.json();
            auth.saveCurrentUser(createdUser);
            alert('??????????? ???????!');
            window.location.href = 'catalog.html';
        } else {
            const error = await response.json();
            alert('?????? ???????????: ' + (error.message || '??????????? ??????'));
        }

} catch (error) {
        console.error('Ошибка при регистрации:', error);
        alert('Не удалось зарегистрироваться. Убедитесь, что JSON Server запущен.');
    }
}

